-- Backfill sub_categories.parent_category_id from Airtable KUNCH_11 source data.
-- Source: Sub-Categories table (633 records), matched by item_name -> parent category name.
-- 602 of 633 rows have a parent in Airtable; 28 are genuinely unlinked there, 3 have no item name.
-- Run the verification query first to confirm every parent name resolves to an existing
-- categories row before applying the UPDATE.

-- ─── 1. Verification: mapping rows whose parent name has no match in categories ───
WITH mapping(item_name, parent_name) AS (
  VALUES
  ('Rope', 'Building Materials'),
  ('Daniel Loan (2m)', 'Loan '),
  ('Doma', 'Tools'),
  ('Air Hose T', 'Building Materials'),
  ('LADA ', 'Transportation'),
  ('Tempered Glass', 'Glass'),
  ('Advances made on Megabit 2018', 'Salary Advances'),
  ('Paint Nastro', 'Building Materials'),
  ('Electrode', 'Electrical Materials'),
  ('Shooter Light', 'Electrical Materials'),
  ('TOT for workshop', 'Property Rent'),
  ('Shebo', 'Building Materials'),
  ('Bell', 'Electrical Materials'),
  ('Hit Gun', 'Tools'),
  ('Polished Brown Granite', 'Granite'),
  ('Block Workers', 'Labor'),
  ('Nail by 8', 'Nail'),
  ('Air hose', 'Plastic'),
  ('80*80', 'Steel'),
  ('Safarian 3mm', 'Safarian'),
  ('Meter Saw ', 'Tools'),
  ('Jotun S4550-g50', 'Paints'),
  ('Lily Plant', 'Components'),
  ('9925', 'Paints'),
  ('Jotun 5208', 'Paints'),
  ('MDF 6mm White', 'MDF'),
  ('Morale 2.5x30', 'Morale'),
  ('Jet Paint', 'Paints'),
  ('Diesel for Generator ', 'Fuel'),
  ('Plate', 'Steel'),
  ('Oslo 51', 'Components'),
  ('PROFIT TAX ', 'Government Expense'),
  ('Gorendayo Work', 'Labor'),
  ('Metal Mesh', 'Steel'),
  ('20*20', 'Steel'),
  ('Veneer Mat Light gray', 'Veneer'),
  ('Fast Anti-Rust', 'Paints'),
  ('Grinding Sand Paper by 120', 'Sand Paper '),
  ('Construction', 'Sub Contrcators'),
  ('Glass Cutting', 'Other Services'),
  ('Screw by 3', 'Screw'),
  ('VRF on ታህሳስ 2018', 'VRF '),
  ('Fuel for Generator', 'Fuel'),
  ('Labor Payments for Nardos', 'Labor'),
  ('Payment For Mohammed', 'Labor'),
  ('Postish', 'Paints'),
  ('Morale 7*5', 'Morale'),
  ('Self Screw 1.9', 'Screw'),
  ('Screw Bit Holder', 'Screw'),
  ('Labor for Girma’s Home', 'Labor'),
  ('Cotton (Cons Purpose)', 'Building Materials'),
  ('Software Update', 'Office Utility '),
  ('Cable', 'Electrical Materials'),
  ('Doctors Glove ', 'Tools'),
  ('BMT Wire', 'Electrical Materials'),
  ('Sliding Door Fitting ', 'Components'),
  ('Teletafi Aluminum Profile ', 'Aluminum'),
  ('Miscellaneous Labor', 'Labor'),
  ('Kuncho Taxes', 'Government Expense'),
  ('Broom', 'Inventory'),
  ('Morale 4*5', 'Morale'),
  ('Panel Light', 'Electrical Materials'),
  ('Filler', 'Building Materials'),
  ('Wheel', 'Inventory'),
  ('Safarian 12mm', 'Safarian'),
  ('M 15L - Fenomasic Rch Matt Base A 15L', 'Paints'),
  ('Cutting Machine', 'Inventory'),
  ('Sand Paper by 60', 'Sand Paper '),
  ('Alcohol', 'Building Materials'),
  ('L Angle', 'Steel'),
  ('Board Screw', 'Screw'),
  ('PVC Deck Flooring', 'Deck'),
  ('Rambo Compressor 50L', 'Tools'),
  ('Workshop Labor ', 'Labor'),
  ('Chalk Gypsum', 'Gypsum'),
  ('Dangote Cement', 'Cement'),
  ('DNF Monthly Tax', 'Government Expense'),
  ('UV DTF', 'Printing'),
  ('Screw by 5', 'Screw'),
  ('587', 'Paints'),
  ('Sand', 'Components'),
  ('VRF on ጥቅምት 2018', 'VRF '),
  ('Labor for Meskel Flower Project', 'Labor'),
  ('Small Car Rent', 'Property Rent'),
  ('Refund on Error Payment', 'FX'),
  ('ARCH Sales Refund', 'Refund'),
  ('Cutting Granite Service', 'Granite'),
  ('Labor for Africa Maritime', 'Labor'),
  ('Double Strip Light', 'Electrical Materials'),
  ('Aluminum Accessories Endale', 'Aluminum'),
  ('UV White', 'UV Wood'),
  ('Megaz', 'Tools'),
  ('Veneer ', 'Veneer'),
  ('Shibo', 'Building Materials'),
  ('Spot Light', 'Electrical Materials'),
  ('Jotun White', 'Paints'),
  ('Clip 24mm', 'Electrical Materials'),
  ('Cable BMT', 'Electrical Materials'),
  ('Finder Rolo Brush', 'Tools'),
  ('Hand Saw', 'Tools'),
  ('Waterproof Switch ', 'Electrical Materials'),
  ('D vella', 'Steel'),
  ('MDF WH Awasa', 'MDF'),
  ('Side Angle', 'Steel'),
  ('Circular Saw', 'Tools'),
  ('Garbage Bag', 'Plastic'),
  ('25*38mm RHS 30', 'Steel'),
  ('Sharpening Disk', 'Building Materials'),
  ('Vita', 'Foam'),
  ('Hard Stone', 'Components'),
  ('Mud', 'Components'),
  ('Machine Service (DNF)', 'Office Expenses '),
  ('Design', 'Sub Contrcators'),
  ('Table wire Tap', 'Components'),
  ('Jotun 12308', 'Paints'),
  ('Nut by 8', 'Steel'),
  ('VRF on Megabit 2018', 'VRF '),
  ('Labor for Endale House', 'Labor'),
  ('Sand Paper by 80', 'Sand Paper '),
  ('Lunch for Workers ', 'Entertainment Expense '),
  ('Waterproof Fountain Strip Light', 'Electrical Materials'),
  ('Breaker by 16A', 'Electrical Materials'),
  ('Solid UV Light Gray', 'UV Wood'),
  ('Fuel for Nati''s car', 'Fuel'),
  ('Nipples', 'Steel'),
  ('W.p bell sw', 'Electrical Materials'),
  ('Jotun 6260', 'Paints'),
  ('Waterproof Socket', 'Electrical Materials'),
  ('Aluminum Profile Endale', 'Aluminum'),
  ('Stucco', 'Paints'),
  ('Plaster', 'Building Materials'),
  ('UV White Spark', 'UV Wood'),
  ('Fayzit', 'Morale'),
  ('Hole Saw', 'Building Materials'),
  ('2.5 BMET Cable', 'Electrical Materials'),
  ('3*4 Cable ', 'Electrical Materials'),
  ('Shower Box', 'Components'),
  ('Plug', 'Electrical Materials'),
  ('L profile ', 'Steel'),
  ('Fasil Labor Payments', 'Labor'),
  ('Chiseler', 'Labor'),
  ('Shooter lights', 'Electrical Materials'),
  ('LED Track Light', 'Electrical Materials'),
  ('Connecter ', 'Electrical Materials'),
  ('25*25', 'Steel'),
  ('MDF White 6mm ', 'MDF'),
  ('Safarian 18mm', 'Safarian'),
  ('Colla', 'Paints'),
  ('Perque Work', 'Sub Contrcators'),
  ('Silver Angle', 'Steel'),
  ('Ajeka', 'Building Materials'),
  ('Machine Maintenance  ', 'Other Services'),
  ('VRF on  መስከረም 2018', 'VRF '),
  ('Shooter Nail by 2', 'Nail'),
  ('Gorendayo', 'Building Materials'),
  ('Strip Light Adapter', 'Electrical Materials'),
  ('CHS 40', 'Steel'),
  ('Paint Gun', 'Tools'),
  ('Cement', 'Cement'),
  ('Laminated Chupped', 'Chupped '),
  ('Nail by 6', 'Building Materials'),
  ('Concert Shooter Nail', 'Nail'),
  ('Electricity Bill', 'Workshop Overhead '),
  ('Green Board Waterproof ', 'Gypsum'),
  ('Putty', 'Putty'),
  ('Food', 'Entertainment Expense '),
  ('Labor Accidents', 'Labor'),
  ('Ppr pipe by 20', 'Tap'),
  ('Grinder Lubricant', 'Building Materials'),
  ('Apple Glue', 'Building Materials'),
  ('Loan to Mathias', 'Loan '),
  ('Thinner ', 'Building Materials'),
  ('Aggregate Labor Wallet', 'Labor'),
  ('Nail', 'Nail'),
  ('Labor For Adwa Stage ', 'Labor'),
  ('Motorcycle', 'Transportation'),
  ('Jotun 8241', 'Paints'),
  ('Personal Cleaning Services', 'Personal withdraws'),
  ('4097', 'Paints'),
  ('Pickup ', 'Transportation'),
  ('Spade Bit', 'Building Materials'),
  ('Abreham Labor Payments', 'Labor'),
  ('R-45', 'Building Materials'),
  ('Laminated MDF', 'MDF'),
  ('Lamera Cutting Bending', 'Steel'),
  ('10580', 'Paints'),
  ('Marker', 'Office Inventory'),
  ('Shera', 'Components'),
  ('Mask', 'Tools'),
  ('Gate Valve by 20mm', 'Tap'),
  ('Paint Work', 'Sub Contrcators'),
  ('Spacers ', 'Inventory'),
  ('Ppr F T by 25', 'Tap'),
  ('Workshop Rent', 'Property Rent'),
  ('LED Driver ', 'Electrical Materials'),
  ('Glass Cleaner', 'Labor'),
  ('Powder Coating', 'Other Services'),
  ('Oven Paint', 'Paints'),
  ('Veneer Sharpening ', 'Other Services'),
  ('Wash Basin_Cabinated Double Bowl', 'Components'),
  ('Scatola Cover', 'Electrical Materials'),
  ('Fast Glue', 'Paints'),
  ('Cleaning Materials', 'Tools'),
  ('Grinding Pad', 'Building Materials'),
  ('40*40*1.5', 'Steel'),
  ('Box Files', 'Office Inventory'),
  ('Hydraulic Slider 50', 'Components'),
  (' Kidus''s Withdrawals ', 'Personal withdraws'),
  ('Dry Wall Screw', 'Screw'),
  ('Fabric', 'Leather Materials'),
  ('Machine Wood Cutting', 'Other Services'),
  ('Handle by 15cm', 'Components'),
  ('Cutting Disk', 'Building Materials'),
  ('Labor for EFF', 'Labor'),
  ('Grinder Coal', 'Building Materials'),
  ('Silicon Sealant ', 'Paints'),
  ('Shovel', 'Tools'),
  ('MDF 6mm NR', 'MDF'),
  ('Carpenter Glove', 'Tools'),
  ('Aluminum U Silver', 'Aluminum'),
  ('Glue ', 'Leather Materials'),
  ('Push Button ', 'Building Materials'),
  ('Punta', 'Punta'),
  ('Gray Board ', 'Leather Materials'),
  ('Jotun TM White ', 'Paints'),
  ('2731', 'Paints'),
  ('Leather Workshop Rent', 'Property Rent'),
  ('Screw by 8', 'Screw'),
  ('Frame Work', 'Sub Contrcators'),
  ('Inner Shark Meter 3m', 'Tools'),
  ('Veneer UV Dark Gray', 'Veneer'),
  ('Interior Design', 'Sub Contrcators'),
  ('Spider Connecter ', 'Steel'),
  ('Self Screw', 'Screw'),
  ('Golden Angle ', 'Steel'),
  ('Madaberiya ', 'Components'),
  ('Strip light Socket', 'Electrical Materials'),
  ('Shooter Nail by 4', 'Nail'),
  ('Socket', 'Electrical Materials'),
  ('Machine Veneer ', 'Veneer'),
  ('Advances made on Yekatit 2018', 'Salary Advances'),
  ('Fountain Work', 'Sub Contrcators'),
  ('DNF Gov''t Contributions', 'Government Expense'),
  ('Dulentin', 'Paints'),
  ('Ppr elbow by 25', 'Tap'),
  ('Printing ', 'Office Expenses '),
  ('Shooter Gun', 'Tools'),
  ('Air Hose Connector', 'Building Materials'),
  ('Omega', 'Steel'),
  ('Iron Shark Screw Head', 'Screw'),
  ('Labor for Bishofu Site', 'Labor'),
  ('DNF VAT', 'Government Expense'),
  ('Soudal Foam', 'Foam'),
  ('Hose Fitting ', 'Building Materials'),
  ('Safarian 6mm', 'Safarian'),
  ('Key', 'Components'),
  ('LED Grille Light', 'Electrical Materials'),
  ('Jotun 53050 ', 'Paints'),
  ('Saoda Foam', 'Foam'),
  ('Sub Contractor for Endale House', 'Sub Contrcators'),
  ('VRF on Miyaziya ', 'VRF '),
  ('Spazari', 'Building Materials'),
  ('Jotun 6029', 'Paints'),
  ('ULURU-11-01 - ULURU-11', 'Components'),
  ('Workshop Branch - 2  Rent', 'Property Rent'),
  ('Jotun 7550', 'Paints'),
  ('Gate Valve by 3/4', 'Tap'),
  ('Chinga', 'Building Materials'),
  ('Jotun 6033', 'Paints'),
  ('Circle Panel Light', 'Electrical Materials'),
  ('10428', 'Paints'),
  ('MDF 6mm', 'MDF'),
  ('0.8 Cable ', 'Electrical Materials'),
  ('Grinding Disk', 'Building Materials'),
  ('Hole Saw Adapter ', 'Tools'),
  ('3025 chianti', 'Paints'),
  ('Wall Double Switch ', 'Electrical Materials'),
  ('Sub Contractor for Sami Apt', 'Sub Contrcators'),
  ('License Plate Penality', 'Penalty'),
  ('Caster Wheel ', 'Components'),
  ('JOTASHILD ETERNA BASE B 15 - Jotashild Eterna Base B 15L ', 'Paints'),
  ('Machine rent ', 'Other Services'),
  ('Largo', 'Sanitary Material'),
  ('Aluminum Light ', 'Electrical Materials'),
  ('Generator Rent', 'Machinery Rental '),
  ('Jotun 8336', 'Paints'),
  ('Breaker by 10', 'Electrical Materials'),
  ('SEG Fabric Printing', 'Printing'),
  ('Battery 90W', 'Inventory'),
  ('Ceramic Works', 'Labor'),
  ('White Spray ', 'Paints'),
  ('Jotun 1020', 'Paints'),
  ('Morale Australia ', 'Morale'),
  ('Rolo Brush ', 'Tools'),
  ('SO D-Wood', 'MDF'),
  ('Jotun 8321', 'Paints'),
  ('Putty Workers ', 'Labor'),
  ('Jotun Black', 'Paints'),
  ('Metal Works ', 'Sub Contrcators'),
  ('Sand paper', 'Sand Paper '),
  ('White PVA', 'Paints'),
  ('50*30', 'Steel'),
  ('LED Trucking rail', 'Electrical Materials'),
  ('Glue Stick', 'Building Materials'),
  ('9913', 'Paints'),
  ('Knauf Board', 'Gypsum'),
  ('Spray gun (pistola)', 'Tools'),
  ('Disc 180', 'Tools'),
  ('Traffic charge ', 'Penalty'),
  ('Jotun 8043 Lux', 'Paints'),
  ('Kadisco 2k pu Lacquer ', 'Paints'),
  ('Aluminum Light Driver', 'Electrical Materials'),
  ('MDF 6mm SZ', 'MDF'),
  ('Labor For Zemen Bank Coaster & Calendar ', 'Labor'),
  ('Strip Light', 'Electrical Materials'),
  ('Gray Filler ', 'Building Materials'),
  ('Veneer Mat White ', 'Veneer'),
  ('Praycot', 'Building Materials'),
  ('Seble Admasu ', 'Loan '),
  ('Jotun 6259', 'Paints'),
  ('Workshop uniform', 'Inventory'),
  ('Labor for Temesgen Project', 'Labor'),
  ('Electrical Work', 'Sub Contrcators'),
  ('Tv panel', 'Steel'),
  ('8252', 'Paints'),
  ('Drawer lock', 'Components'),
  ('Cat6 (BMET) ', 'Electrical Materials'),
  ('Workshop Pipe Fixing', 'Other Services'),
  ('Shenbeko Handle ', 'Components'),
  ('Cutter Knife ', 'Tools'),
  ('60*60', 'Steel'),
  ('Fisher', 'Screw'),
  ('Newspaper', 'Building Materials'),
  ('Office Rent', 'Property Rent'),
  ('Granite Cutting', 'Granite'),
  ('Black Aluminum Profile by 2cm', 'Aluminum'),
  ('Blue Leather ', 'Leather Materials'),
  ('Mattress', 'Inventory'),
  ('White Veneer', 'Veneer'),
  ('Painters', 'Labor'),
  ('VRF On ነሐሴ 2017', 'VRF '),
  ('20 Feet Container ', 'Inventory'),
  ('Wire', 'Electrical Materials'),
  ('2x1.5 Cable', 'Electrical Materials'),
  ('Workshop Entertainment Expense ', 'Entertainment Expense '),
  ('Plastic Table Leg', 'Components'),
  ('Cleaner', 'Labor'),
  ('Screw Driver ', 'Tools'),
  ('Abro Spray Paint', 'Paints'),
  ('Adapter', 'Tools'),
  ('MDF 10MM', 'MDF'),
  ('Ride', 'Transportation'),
  ('Slider by 30cm', 'Components'),
  ('Gravel ', 'Components'),
  ('Sofa ', 'Components'),
  ('Gypsum ', 'Gypsum'),
  ('Ega Screw ', 'Screw'),
  ('Drill', 'Tools'),
  ('Meter ', 'Tools'),
  ('Yonatan Nega Withdraws ', 'Personal withdraws'),
  ('8044', 'Paints'),
  ('Band aid', 'First Aid Materials'),
  ('Sticker Printing', 'Printing'),
  ('Rebar', 'Steel'),
  ('Jotun Egg White', 'Paints'),
  ('Cream', 'Leather Materials'),
  ('Golden Screw', 'Screw'),
  ('Jotun 1001', 'Paints'),
  ('Rain Chain ', 'Steel'),
  ('Scatola', 'Electrical Materials'),
  ('Switch for Pole ', 'Electrical Materials'),
  ('Carpet', 'Components'),
  ('Hand Sand Paper ', 'Sand Paper '),
  ('Edge ', 'Building Materials'),
  ('SO UV DG ', 'MDF'),
  ('Handle by 30cm', 'Components'),
  ('Rake ', 'Building Materials'),
  ('Grinding Sand Paper by 80', 'Sand Paper '),
  ('18mm foam', 'Foam'),
  ('Panel Light 18w', 'Electrical Materials'),
  ('PVA Primer ', 'Paints'),
  ('Jotun 1364LUX', 'Paints'),
  ('Black Cow Leather ', 'Leather Materials'),
  ('Aluminum Profile ', 'Aluminum'),
  ('Hydraulic Hinge', 'Components'),
  ('Veneer by 2.2cm', 'Veneer'),
  ('Coat Angle', 'Components'),
  ('2 LT Truck', 'Fuel'),
  ('Neon Strip Light ', 'Electrical Materials'),
  ('Zabiya', 'Building Materials'),
  ('Chama', 'Building Materials'),
  ('Black Matt', 'Paints'),
  ('40*40*2', 'Steel'),
  ('Mixed paint', 'Paints'),
  ('Sofa Legs', 'Components'),
  ('Solid WH MDF', 'MDF'),
  ('Office WiFi', 'Office Expenses '),
  ('Labor for AFCA', 'Labor'),
  ('CHS 25', 'Steel'),
  ('8596', 'Paints'),
  ('Veneer Mat-MC', 'Veneer'),
  ('Africa Gypsum', 'Gypsum'),
  ('Handle', 'Components'),
  ('Tube', 'Leather Materials'),
  ('Jotun White ', 'Paints'),
  ('Paper Tubes ', 'Components'),
  ('1.5 Euro Wire ', 'Electrical Materials'),
  ('PPR gate Valve 1/2', 'Tap'),
  ('(IM)WHITE - Fenomastic Rch Matt (Im) White', 'Paints'),
  ('Labor for ACS 2', 'Labor'),
  ('Shooter Nail', 'Nail'),
  ('Withholding Expense Paid ', 'Government Expense'),
  ('Green Light Strip Socket', 'Electrical Materials'),
  ('Aluminum Cladding', 'Aluminum'),
  ('Abel''s Withdrawals', 'Personal withdraws'),
  ('Thread Black ', 'Leather Materials'),
  ('30*30', 'Steel'),
  ('Diamond Disk', 'Building Materials'),
  ('Single Black Switch ', 'Electrical Materials'),
  ('Solid UV White', 'UV Wood'),
  ('Aschalew Mihiret Withdrawals', 'Personal withdraws'),
  ('Cash Register Machine ', 'Office Expenses '),
  ('Plywood Imported', 'Morale'),
  ('Wanza', 'Wood'),
  ('LEATHER Sales Refund', 'Refund'),
  ('Solid pc sheet', 'Plastic'),
  ('Loading/Unloading ', 'Labor'),
  ('Wall Light', 'Electrical Materials'),
  ('Grinder 750W', 'Tools'),
  ('Screw Head ', 'Screw'),
  ('Channel', 'Steel'),
  ('Structural Silicon', 'Paints'),
  ('Sub Contractor for Assefa House', 'Sub Contrcators'),
  ('Paper for Calendar ', 'Components'),
  ('Income And Pension Tax', 'Government Expense'),
  ('Payment for Officials', 'Miscellaneous '),
  ('Foam cladding', 'Foam'),
  ('Oil change', 'Other Services'),
  ('Ferro Stucco', 'Paints'),
  ('Guroro Conduit 13mm', 'Electrical Materials'),
  ('Nati''s Withdrawals', 'Personal withdraws'),
  ('VRF on Genbot', 'VRF '),
  ('Lock', 'Components'),
  ('10342', 'Paints'),
  ('Sponge', 'Building Materials'),
  ('Screw', 'Screw'),
  ('Machine Service (Kuncho)', 'Office Expenses '),
  ('Jotun 8337', 'Paints'),
  ('White Putty', 'Putty'),
  ('Nebiyat ', 'Loan '),
  ('Fuel For Tacoma', 'Fuel'),
  ('General Sub Contractor Work', 'Sub Contrcators'),
  ('Screw by 1.5', 'Screw'),
  ('D vella ', 'Steel'),
  ('Green Light Strip ', 'Electrical Materials'),
  ('Gate Valve by 25mm', 'Tap'),
  ('Penalty for receipt submission', 'Penalty'),
  ('Shelf Pin', 'Components'),
  ('4625', 'Paints'),
  ('Cartoon', 'Leather Materials'),
  ('Fuel for 2LT Pickup ', 'Fuel'),
  ('Door', 'Components'),
  ('MDF OverSized', 'MDF'),
  ('Crane', 'Machinery Rental '),
  ('VRF on ህዳር 2018', 'VRF '),
  ('Mop', 'Inventory'),
  ('CNC Punta by 6', 'Punta'),
  ('Veneer Gray', 'Veneer'),
  ('Sanitary Materials', 'Building Materials'),
  ('Toner', 'Office Inventory'),
  ('RHS ', 'Steel'),
  ('Hawassa MDF 18mm ', 'MDF'),
  ('RG 45', 'Electrical Materials'),
  ('Aluminum Track Channel', 'Aluminum'),
  ('Labor for Solomon Garden', 'Labor'),
  ('Grass', 'Components'),
  ('Sand Paper by 360', 'Sand Paper '),
  ('PPR Pipe by 25', 'Tap'),
  ('Veneer White', 'Veneer'),
  ('VRF on TIR 2018', 'VRF '),
  ('Aluminum Profile Office ', 'Aluminum'),
  ('Veneer UV White', 'Veneer'),
  ('A4 Paper ', 'Office Inventory'),
  ('Grinding Sand', 'Sand Paper '),
  ('Gypsum Work', 'Labor'),
  ('Aggregate Workers', 'Labor'),
  ('Water and Electricity Bill', 'Office Utility '),
  ('Nastro', 'Electrical Materials'),
  ('Disc 320', 'Tools'),
  ('Abeselom Loan ', 'Loan '),
  ('Gray Putty', 'Putty'),
  ('DNF Profit Tax', 'Government Expense'),
  ('Apel Foam', 'Foam'),
  ('C nail', 'Nail'),
  ('CNC Punta by 4', 'Punta'),
  ('Concert Admixture  ', 'Components'),
  ('Installation for Carpet', 'Other Services'),
  ('Jacuzzi', 'Components'),
  ('Bell Sou DingDong', 'Electrical Materials'),
  ('Trunking 10x20', 'Electrical Materials'),
  ('Labor for Wafa (AAICC)', 'Labor'),
  ('Jotun 1060', 'Paints'),
  ('MDF 18MM Asela', 'MDF'),
  ('Glass ', 'Glass'),
  ('Spuruso (coating)', 'Paints'),
  ('Waste Disposal ', 'Labor'),
  ('Chalk Blade', 'Tools'),
  ('Journal Paper', 'Office Expenses '),
  ('VRF on Yekatit 2018', 'VRF '),
  ('Abel''s Personal Payments', 'Loan '),
  ('Cement Board', 'Cement'),
  ('Trunking', 'Electrical Materials'),
  ('Metal bending ', 'Other Services'),
  ('Tap', 'Tap'),
  ('Veneer Mat', 'Veneer'),
  ('Angle', 'Steel'),
  ('2.5 Euro Wire', 'Electrical Materials'),
  ('Circle saw', 'Tools'),
  ('Aluminum Cladding Black', 'Aluminum'),
  ('MDF 18mm', 'MDF'),
  ('Jotun stucco ', 'Paints'),
  ('Conduit ', 'Electrical Materials'),
  ('Ppr reducer by 25x20', 'Tap'),
  ('U Aluminum ', 'Aluminum'),
  ('Screen Rent', 'Equipment Rental'),
  ('Clip', 'Electrical Materials'),
  ('Workshop Petty', 'PETTY'),
  ('L beret', 'Steel'),
  ('Scotch Tape', 'Electrical Materials'),
  ('9016 ', 'Paints'),
  ('JOTSH. TEX MEDUIIM WHITE 15 - Jotashild Tex Medium White 15L', 'Paints'),
  ('MDF 12MM', 'MDF'),
  ('Stage', 'Machinery Rental '),
  ('2.5x3 Cable', 'Electrical Materials'),
  ('Granite Polished H. Brown T-30', 'Granite'),
  ('Scaffolding ', 'Labor'),
  ('Olso 51', 'Building Materials'),
  ('Electrical Motorbike', 'Inventory'),
  ('Plastic glass (mayka)', 'Glass'),
  ('Scatola 10*10', 'Electrical Materials'),
  ('Wire cap', 'Electrical Materials'),
  ('Roller ', 'Building Materials'),
  ('Jotun 6032', 'Paints'),
  ('0099', 'Paints'),
  ('Plastic Bag', 'Plastic'),
  ('Shadow Drive', 'Electrical Materials'),
  ('Jotun 5004LUX', 'Paints'),
  ('Tire service ', 'Other Services'),
  ('Lamp 30w', 'Electrical Materials'),
  ('Nifas Silk Paint', 'Paints'),
  ('Yearly Tender Subscription', 'Marketing Expense'),
  ('Double Switch', 'Electrical Materials'),
  ('Single Socket', 'Electrical Materials'),
  ('Stapler Wire', 'Building Materials'),
  ('Anchor Bolt', 'Screw'),
  ('Jotun 0587', 'Paints'),
  ('Dinner For late night labor', 'Entertainment Expense '),
  ('Meter Tap by 5m', 'Tools'),
  ('MDF 8mm', 'MDF'),
  ('Balast for triple strip light', 'Electrical Materials'),
  ('Kacha', 'Building Materials'),
  ('Cutter', 'Tools'),
  ('Sand Paper by 120', 'Sand Paper '),
  ('CHS 50', 'Steel'),
  ('Isuzu ', 'Transportation'),
  ('Strip Light Drive', 'Electrical Materials'),
  ('Balast for Strip Light', 'Electrical Materials'),
  ('VAT WHT', 'Government Expense'),
  ('Labor for National Bank', 'Labor'),
  ('Slider Clamp', 'Building Materials'),
  ('Chalk Work', 'Labor'),
  ('PPR Tap 1/2', 'Tap'),
  ('Guroro Conduit 16', 'Electrical Materials'),
  ('Fasha', 'Building Materials'),
  ('Shooter Nail by 3', 'Nail'),
  ('IM) RCH MATT - Fenomastic Rch Matt (Im) Base B ', 'Paints'),
  ('T5 Light', 'Electrical Materials'),
  ('Package Plastic', 'Plastic'),
  ('Slider by 50cm', 'Components'),
  ('Brush', 'Tools'),
  ('VRF on ሀምሌ 2017', 'VRF '),
  ('IVECO Fuel', 'Fuel'),
  ('Coupling ', 'Building Materials'),
  ('Labor for Italy Africa', 'Labor'),
  ('Scatola 6*10', 'Electrical Materials'),
  ('Light Box', 'Components'),
  ('Waterproof light', 'Electrical Materials'),
  ('MDF WHITE 18MM', 'MDF'),
  ('Total Laser Level ', 'Tools'),
  ('Hydraulic Slider', 'Components'),
  ('Spray Mastish', 'Paints'),
  ('10235 summer sun', 'Paints'),
  ('Lamera', 'Steel'),
  ('Small Car Fuel', 'Fuel'),
  ('Aluminum Silver', 'Aluminum'),
  ('Overtime', 'Salary'),
  ('Gondar Personal Withdrawals ', 'Personal withdraws'),
  ('Solid Mat', 'UV Wood'),
  ('Cable HSS', 'Electrical Materials'),
  ('Thread bar by 8mm', 'Steel'),
  ('Cash Register Machine Cable', 'Office Inventory'),
  ('Receipt Printing', 'Government Expense')
)
SELECT m.item_name, m.parent_name
FROM mapping m
LEFT JOIN categories c ON c.category_name = m.parent_name
WHERE c.id IS NULL;

-- ─── 2. Backfill: only touches rows where parent_category_id is currently NULL ───
WITH mapping(item_name, parent_name) AS (
  VALUES
  ('Rope', 'Building Materials'),
  ('Daniel Loan (2m)', 'Loan '),
  ('Doma', 'Tools'),
  ('Air Hose T', 'Building Materials'),
  ('LADA ', 'Transportation'),
  ('Tempered Glass', 'Glass'),
  ('Advances made on Megabit 2018', 'Salary Advances'),
  ('Paint Nastro', 'Building Materials'),
  ('Electrode', 'Electrical Materials'),
  ('Shooter Light', 'Electrical Materials'),
  ('TOT for workshop', 'Property Rent'),
  ('Shebo', 'Building Materials'),
  ('Bell', 'Electrical Materials'),
  ('Hit Gun', 'Tools'),
  ('Polished Brown Granite', 'Granite'),
  ('Block Workers', 'Labor'),
  ('Nail by 8', 'Nail'),
  ('Air hose', 'Plastic'),
  ('80*80', 'Steel'),
  ('Safarian 3mm', 'Safarian'),
  ('Meter Saw ', 'Tools'),
  ('Jotun S4550-g50', 'Paints'),
  ('Lily Plant', 'Components'),
  ('9925', 'Paints'),
  ('Jotun 5208', 'Paints'),
  ('MDF 6mm White', 'MDF'),
  ('Morale 2.5x30', 'Morale'),
  ('Jet Paint', 'Paints'),
  ('Diesel for Generator ', 'Fuel'),
  ('Plate', 'Steel'),
  ('Oslo 51', 'Components'),
  ('PROFIT TAX ', 'Government Expense'),
  ('Gorendayo Work', 'Labor'),
  ('Metal Mesh', 'Steel'),
  ('20*20', 'Steel'),
  ('Veneer Mat Light gray', 'Veneer'),
  ('Fast Anti-Rust', 'Paints'),
  ('Grinding Sand Paper by 120', 'Sand Paper '),
  ('Construction', 'Sub Contrcators'),
  ('Glass Cutting', 'Other Services'),
  ('Screw by 3', 'Screw'),
  ('VRF on ታህሳስ 2018', 'VRF '),
  ('Fuel for Generator', 'Fuel'),
  ('Labor Payments for Nardos', 'Labor'),
  ('Payment For Mohammed', 'Labor'),
  ('Postish', 'Paints'),
  ('Morale 7*5', 'Morale'),
  ('Self Screw 1.9', 'Screw'),
  ('Screw Bit Holder', 'Screw'),
  ('Labor for Girma’s Home', 'Labor'),
  ('Cotton (Cons Purpose)', 'Building Materials'),
  ('Software Update', 'Office Utility '),
  ('Cable', 'Electrical Materials'),
  ('Doctors Glove ', 'Tools'),
  ('BMT Wire', 'Electrical Materials'),
  ('Sliding Door Fitting ', 'Components'),
  ('Teletafi Aluminum Profile ', 'Aluminum'),
  ('Miscellaneous Labor', 'Labor'),
  ('Kuncho Taxes', 'Government Expense'),
  ('Broom', 'Inventory'),
  ('Morale 4*5', 'Morale'),
  ('Panel Light', 'Electrical Materials'),
  ('Filler', 'Building Materials'),
  ('Wheel', 'Inventory'),
  ('Safarian 12mm', 'Safarian'),
  ('M 15L - Fenomasic Rch Matt Base A 15L', 'Paints'),
  ('Cutting Machine', 'Inventory'),
  ('Sand Paper by 60', 'Sand Paper '),
  ('Alcohol', 'Building Materials'),
  ('L Angle', 'Steel'),
  ('Board Screw', 'Screw'),
  ('PVC Deck Flooring', 'Deck'),
  ('Rambo Compressor 50L', 'Tools'),
  ('Workshop Labor ', 'Labor'),
  ('Chalk Gypsum', 'Gypsum'),
  ('Dangote Cement', 'Cement'),
  ('DNF Monthly Tax', 'Government Expense'),
  ('UV DTF', 'Printing'),
  ('Screw by 5', 'Screw'),
  ('587', 'Paints'),
  ('Sand', 'Components'),
  ('VRF on ጥቅምት 2018', 'VRF '),
  ('Labor for Meskel Flower Project', 'Labor'),
  ('Small Car Rent', 'Property Rent'),
  ('Refund on Error Payment', 'FX'),
  ('ARCH Sales Refund', 'Refund'),
  ('Cutting Granite Service', 'Granite'),
  ('Labor for Africa Maritime', 'Labor'),
  ('Double Strip Light', 'Electrical Materials'),
  ('Aluminum Accessories Endale', 'Aluminum'),
  ('UV White', 'UV Wood'),
  ('Megaz', 'Tools'),
  ('Veneer ', 'Veneer'),
  ('Shibo', 'Building Materials'),
  ('Spot Light', 'Electrical Materials'),
  ('Jotun White', 'Paints'),
  ('Clip 24mm', 'Electrical Materials'),
  ('Cable BMT', 'Electrical Materials'),
  ('Finder Rolo Brush', 'Tools'),
  ('Hand Saw', 'Tools'),
  ('Waterproof Switch ', 'Electrical Materials'),
  ('D vella', 'Steel'),
  ('MDF WH Awasa', 'MDF'),
  ('Side Angle', 'Steel'),
  ('Circular Saw', 'Tools'),
  ('Garbage Bag', 'Plastic'),
  ('25*38mm RHS 30', 'Steel'),
  ('Sharpening Disk', 'Building Materials'),
  ('Vita', 'Foam'),
  ('Hard Stone', 'Components'),
  ('Mud', 'Components'),
  ('Machine Service (DNF)', 'Office Expenses '),
  ('Design', 'Sub Contrcators'),
  ('Table wire Tap', 'Components'),
  ('Jotun 12308', 'Paints'),
  ('Nut by 8', 'Steel'),
  ('VRF on Megabit 2018', 'VRF '),
  ('Labor for Endale House', 'Labor'),
  ('Sand Paper by 80', 'Sand Paper '),
  ('Lunch for Workers ', 'Entertainment Expense '),
  ('Waterproof Fountain Strip Light', 'Electrical Materials'),
  ('Breaker by 16A', 'Electrical Materials'),
  ('Solid UV Light Gray', 'UV Wood'),
  ('Fuel for Nati''s car', 'Fuel'),
  ('Nipples', 'Steel'),
  ('W.p bell sw', 'Electrical Materials'),
  ('Jotun 6260', 'Paints'),
  ('Waterproof Socket', 'Electrical Materials'),
  ('Aluminum Profile Endale', 'Aluminum'),
  ('Stucco', 'Paints'),
  ('Plaster', 'Building Materials'),
  ('UV White Spark', 'UV Wood'),
  ('Fayzit', 'Morale'),
  ('Hole Saw', 'Building Materials'),
  ('2.5 BMET Cable', 'Electrical Materials'),
  ('3*4 Cable ', 'Electrical Materials'),
  ('Shower Box', 'Components'),
  ('Plug', 'Electrical Materials'),
  ('L profile ', 'Steel'),
  ('Fasil Labor Payments', 'Labor'),
  ('Chiseler', 'Labor'),
  ('Shooter lights', 'Electrical Materials'),
  ('LED Track Light', 'Electrical Materials'),
  ('Connecter ', 'Electrical Materials'),
  ('25*25', 'Steel'),
  ('MDF White 6mm ', 'MDF'),
  ('Safarian 18mm', 'Safarian'),
  ('Colla', 'Paints'),
  ('Perque Work', 'Sub Contrcators'),
  ('Silver Angle', 'Steel'),
  ('Ajeka', 'Building Materials'),
  ('Machine Maintenance  ', 'Other Services'),
  ('VRF on  መስከረም 2018', 'VRF '),
  ('Shooter Nail by 2', 'Nail'),
  ('Gorendayo', 'Building Materials'),
  ('Strip Light Adapter', 'Electrical Materials'),
  ('CHS 40', 'Steel'),
  ('Paint Gun', 'Tools'),
  ('Cement', 'Cement'),
  ('Laminated Chupped', 'Chupped '),
  ('Nail by 6', 'Building Materials'),
  ('Concert Shooter Nail', 'Nail'),
  ('Electricity Bill', 'Workshop Overhead '),
  ('Green Board Waterproof ', 'Gypsum'),
  ('Putty', 'Putty'),
  ('Food', 'Entertainment Expense '),
  ('Labor Accidents', 'Labor'),
  ('Ppr pipe by 20', 'Tap'),
  ('Grinder Lubricant', 'Building Materials'),
  ('Apple Glue', 'Building Materials'),
  ('Loan to Mathias', 'Loan '),
  ('Thinner ', 'Building Materials'),
  ('Aggregate Labor Wallet', 'Labor'),
  ('Nail', 'Nail'),
  ('Labor For Adwa Stage ', 'Labor'),
  ('Motorcycle', 'Transportation'),
  ('Jotun 8241', 'Paints'),
  ('Personal Cleaning Services', 'Personal withdraws'),
  ('4097', 'Paints'),
  ('Pickup ', 'Transportation'),
  ('Spade Bit', 'Building Materials'),
  ('Abreham Labor Payments', 'Labor'),
  ('R-45', 'Building Materials'),
  ('Laminated MDF', 'MDF'),
  ('Lamera Cutting Bending', 'Steel'),
  ('10580', 'Paints'),
  ('Marker', 'Office Inventory'),
  ('Shera', 'Components'),
  ('Mask', 'Tools'),
  ('Gate Valve by 20mm', 'Tap'),
  ('Paint Work', 'Sub Contrcators'),
  ('Spacers ', 'Inventory'),
  ('Ppr F T by 25', 'Tap'),
  ('Workshop Rent', 'Property Rent'),
  ('LED Driver ', 'Electrical Materials'),
  ('Glass Cleaner', 'Labor'),
  ('Powder Coating', 'Other Services'),
  ('Oven Paint', 'Paints'),
  ('Veneer Sharpening ', 'Other Services'),
  ('Wash Basin_Cabinated Double Bowl', 'Components'),
  ('Scatola Cover', 'Electrical Materials'),
  ('Fast Glue', 'Paints'),
  ('Cleaning Materials', 'Tools'),
  ('Grinding Pad', 'Building Materials'),
  ('40*40*1.5', 'Steel'),
  ('Box Files', 'Office Inventory'),
  ('Hydraulic Slider 50', 'Components'),
  (' Kidus''s Withdrawals ', 'Personal withdraws'),
  ('Dry Wall Screw', 'Screw'),
  ('Fabric', 'Leather Materials'),
  ('Machine Wood Cutting', 'Other Services'),
  ('Handle by 15cm', 'Components'),
  ('Cutting Disk', 'Building Materials'),
  ('Labor for EFF', 'Labor'),
  ('Grinder Coal', 'Building Materials'),
  ('Silicon Sealant ', 'Paints'),
  ('Shovel', 'Tools'),
  ('MDF 6mm NR', 'MDF'),
  ('Carpenter Glove', 'Tools'),
  ('Aluminum U Silver', 'Aluminum'),
  ('Glue ', 'Leather Materials'),
  ('Push Button ', 'Building Materials'),
  ('Punta', 'Punta'),
  ('Gray Board ', 'Leather Materials'),
  ('Jotun TM White ', 'Paints'),
  ('2731', 'Paints'),
  ('Leather Workshop Rent', 'Property Rent'),
  ('Screw by 8', 'Screw'),
  ('Frame Work', 'Sub Contrcators'),
  ('Inner Shark Meter 3m', 'Tools'),
  ('Veneer UV Dark Gray', 'Veneer'),
  ('Interior Design', 'Sub Contrcators'),
  ('Spider Connecter ', 'Steel'),
  ('Self Screw', 'Screw'),
  ('Golden Angle ', 'Steel'),
  ('Madaberiya ', 'Components'),
  ('Strip light Socket', 'Electrical Materials'),
  ('Shooter Nail by 4', 'Nail'),
  ('Socket', 'Electrical Materials'),
  ('Machine Veneer ', 'Veneer'),
  ('Advances made on Yekatit 2018', 'Salary Advances'),
  ('Fountain Work', 'Sub Contrcators'),
  ('DNF Gov''t Contributions', 'Government Expense'),
  ('Dulentin', 'Paints'),
  ('Ppr elbow by 25', 'Tap'),
  ('Printing ', 'Office Expenses '),
  ('Shooter Gun', 'Tools'),
  ('Air Hose Connector', 'Building Materials'),
  ('Omega', 'Steel'),
  ('Iron Shark Screw Head', 'Screw'),
  ('Labor for Bishofu Site', 'Labor'),
  ('DNF VAT', 'Government Expense'),
  ('Soudal Foam', 'Foam'),
  ('Hose Fitting ', 'Building Materials'),
  ('Safarian 6mm', 'Safarian'),
  ('Key', 'Components'),
  ('LED Grille Light', 'Electrical Materials'),
  ('Jotun 53050 ', 'Paints'),
  ('Saoda Foam', 'Foam'),
  ('Sub Contractor for Endale House', 'Sub Contrcators'),
  ('VRF on Miyaziya ', 'VRF '),
  ('Spazari', 'Building Materials'),
  ('Jotun 6029', 'Paints'),
  ('ULURU-11-01 - ULURU-11', 'Components'),
  ('Workshop Branch - 2  Rent', 'Property Rent'),
  ('Jotun 7550', 'Paints'),
  ('Gate Valve by 3/4', 'Tap'),
  ('Chinga', 'Building Materials'),
  ('Jotun 6033', 'Paints'),
  ('Circle Panel Light', 'Electrical Materials'),
  ('10428', 'Paints'),
  ('MDF 6mm', 'MDF'),
  ('0.8 Cable ', 'Electrical Materials'),
  ('Grinding Disk', 'Building Materials'),
  ('Hole Saw Adapter ', 'Tools'),
  ('3025 chianti', 'Paints'),
  ('Wall Double Switch ', 'Electrical Materials'),
  ('Sub Contractor for Sami Apt', 'Sub Contrcators'),
  ('License Plate Penality', 'Penalty'),
  ('Caster Wheel ', 'Components'),
  ('JOTASHILD ETERNA BASE B 15 - Jotashild Eterna Base B 15L ', 'Paints'),
  ('Machine rent ', 'Other Services'),
  ('Largo', 'Sanitary Material'),
  ('Aluminum Light ', 'Electrical Materials'),
  ('Generator Rent', 'Machinery Rental '),
  ('Jotun 8336', 'Paints'),
  ('Breaker by 10', 'Electrical Materials'),
  ('SEG Fabric Printing', 'Printing'),
  ('Battery 90W', 'Inventory'),
  ('Ceramic Works', 'Labor'),
  ('White Spray ', 'Paints'),
  ('Jotun 1020', 'Paints'),
  ('Morale Australia ', 'Morale'),
  ('Rolo Brush ', 'Tools'),
  ('SO D-Wood', 'MDF'),
  ('Jotun 8321', 'Paints'),
  ('Putty Workers ', 'Labor'),
  ('Jotun Black', 'Paints'),
  ('Metal Works ', 'Sub Contrcators'),
  ('Sand paper', 'Sand Paper '),
  ('White PVA', 'Paints'),
  ('50*30', 'Steel'),
  ('LED Trucking rail', 'Electrical Materials'),
  ('Glue Stick', 'Building Materials'),
  ('9913', 'Paints'),
  ('Knauf Board', 'Gypsum'),
  ('Spray gun (pistola)', 'Tools'),
  ('Disc 180', 'Tools'),
  ('Traffic charge ', 'Penalty'),
  ('Jotun 8043 Lux', 'Paints'),
  ('Kadisco 2k pu Lacquer ', 'Paints'),
  ('Aluminum Light Driver', 'Electrical Materials'),
  ('MDF 6mm SZ', 'MDF'),
  ('Labor For Zemen Bank Coaster & Calendar ', 'Labor'),
  ('Strip Light', 'Electrical Materials'),
  ('Gray Filler ', 'Building Materials'),
  ('Veneer Mat White ', 'Veneer'),
  ('Praycot', 'Building Materials'),
  ('Seble Admasu ', 'Loan '),
  ('Jotun 6259', 'Paints'),
  ('Workshop uniform', 'Inventory'),
  ('Labor for Temesgen Project', 'Labor'),
  ('Electrical Work', 'Sub Contrcators'),
  ('Tv panel', 'Steel'),
  ('8252', 'Paints'),
  ('Drawer lock', 'Components'),
  ('Cat6 (BMET) ', 'Electrical Materials'),
  ('Workshop Pipe Fixing', 'Other Services'),
  ('Shenbeko Handle ', 'Components'),
  ('Cutter Knife ', 'Tools'),
  ('60*60', 'Steel'),
  ('Fisher', 'Screw'),
  ('Newspaper', 'Building Materials'),
  ('Office Rent', 'Property Rent'),
  ('Granite Cutting', 'Granite'),
  ('Black Aluminum Profile by 2cm', 'Aluminum'),
  ('Blue Leather ', 'Leather Materials'),
  ('Mattress', 'Inventory'),
  ('White Veneer', 'Veneer'),
  ('Painters', 'Labor'),
  ('VRF On ነሐሴ 2017', 'VRF '),
  ('20 Feet Container ', 'Inventory'),
  ('Wire', 'Electrical Materials'),
  ('2x1.5 Cable', 'Electrical Materials'),
  ('Workshop Entertainment Expense ', 'Entertainment Expense '),
  ('Plastic Table Leg', 'Components'),
  ('Cleaner', 'Labor'),
  ('Screw Driver ', 'Tools'),
  ('Abro Spray Paint', 'Paints'),
  ('Adapter', 'Tools'),
  ('MDF 10MM', 'MDF'),
  ('Ride', 'Transportation'),
  ('Slider by 30cm', 'Components'),
  ('Gravel ', 'Components'),
  ('Sofa ', 'Components'),
  ('Gypsum ', 'Gypsum'),
  ('Ega Screw ', 'Screw'),
  ('Drill', 'Tools'),
  ('Meter ', 'Tools'),
  ('Yonatan Nega Withdraws ', 'Personal withdraws'),
  ('8044', 'Paints'),
  ('Band aid', 'First Aid Materials'),
  ('Sticker Printing', 'Printing'),
  ('Rebar', 'Steel'),
  ('Jotun Egg White', 'Paints'),
  ('Cream', 'Leather Materials'),
  ('Golden Screw', 'Screw'),
  ('Jotun 1001', 'Paints'),
  ('Rain Chain ', 'Steel'),
  ('Scatola', 'Electrical Materials'),
  ('Switch for Pole ', 'Electrical Materials'),
  ('Carpet', 'Components'),
  ('Hand Sand Paper ', 'Sand Paper '),
  ('Edge ', 'Building Materials'),
  ('SO UV DG ', 'MDF'),
  ('Handle by 30cm', 'Components'),
  ('Rake ', 'Building Materials'),
  ('Grinding Sand Paper by 80', 'Sand Paper '),
  ('18mm foam', 'Foam'),
  ('Panel Light 18w', 'Electrical Materials'),
  ('PVA Primer ', 'Paints'),
  ('Jotun 1364LUX', 'Paints'),
  ('Black Cow Leather ', 'Leather Materials'),
  ('Aluminum Profile ', 'Aluminum'),
  ('Hydraulic Hinge', 'Components'),
  ('Veneer by 2.2cm', 'Veneer'),
  ('Coat Angle', 'Components'),
  ('2 LT Truck', 'Fuel'),
  ('Neon Strip Light ', 'Electrical Materials'),
  ('Zabiya', 'Building Materials'),
  ('Chama', 'Building Materials'),
  ('Black Matt', 'Paints'),
  ('40*40*2', 'Steel'),
  ('Mixed paint', 'Paints'),
  ('Sofa Legs', 'Components'),
  ('Solid WH MDF', 'MDF'),
  ('Office WiFi', 'Office Expenses '),
  ('Labor for AFCA', 'Labor'),
  ('CHS 25', 'Steel'),
  ('8596', 'Paints'),
  ('Veneer Mat-MC', 'Veneer'),
  ('Africa Gypsum', 'Gypsum'),
  ('Handle', 'Components'),
  ('Tube', 'Leather Materials'),
  ('Jotun White ', 'Paints'),
  ('Paper Tubes ', 'Components'),
  ('1.5 Euro Wire ', 'Electrical Materials'),
  ('PPR gate Valve 1/2', 'Tap'),
  ('(IM)WHITE - Fenomastic Rch Matt (Im) White', 'Paints'),
  ('Labor for ACS 2', 'Labor'),
  ('Shooter Nail', 'Nail'),
  ('Withholding Expense Paid ', 'Government Expense'),
  ('Green Light Strip Socket', 'Electrical Materials'),
  ('Aluminum Cladding', 'Aluminum'),
  ('Abel''s Withdrawals', 'Personal withdraws'),
  ('Thread Black ', 'Leather Materials'),
  ('30*30', 'Steel'),
  ('Diamond Disk', 'Building Materials'),
  ('Single Black Switch ', 'Electrical Materials'),
  ('Solid UV White', 'UV Wood'),
  ('Aschalew Mihiret Withdrawals', 'Personal withdraws'),
  ('Cash Register Machine ', 'Office Expenses '),
  ('Plywood Imported', 'Morale'),
  ('Wanza', 'Wood'),
  ('LEATHER Sales Refund', 'Refund'),
  ('Solid pc sheet', 'Plastic'),
  ('Loading/Unloading ', 'Labor'),
  ('Wall Light', 'Electrical Materials'),
  ('Grinder 750W', 'Tools'),
  ('Screw Head ', 'Screw'),
  ('Channel', 'Steel'),
  ('Structural Silicon', 'Paints'),
  ('Sub Contractor for Assefa House', 'Sub Contrcators'),
  ('Paper for Calendar ', 'Components'),
  ('Income And Pension Tax', 'Government Expense'),
  ('Payment for Officials', 'Miscellaneous '),
  ('Foam cladding', 'Foam'),
  ('Oil change', 'Other Services'),
  ('Ferro Stucco', 'Paints'),
  ('Guroro Conduit 13mm', 'Electrical Materials'),
  ('Nati''s Withdrawals', 'Personal withdraws'),
  ('VRF on Genbot', 'VRF '),
  ('Lock', 'Components'),
  ('10342', 'Paints'),
  ('Sponge', 'Building Materials'),
  ('Screw', 'Screw'),
  ('Machine Service (Kuncho)', 'Office Expenses '),
  ('Jotun 8337', 'Paints'),
  ('White Putty', 'Putty'),
  ('Nebiyat ', 'Loan '),
  ('Fuel For Tacoma', 'Fuel'),
  ('General Sub Contractor Work', 'Sub Contrcators'),
  ('Screw by 1.5', 'Screw'),
  ('D vella ', 'Steel'),
  ('Green Light Strip ', 'Electrical Materials'),
  ('Gate Valve by 25mm', 'Tap'),
  ('Penalty for receipt submission', 'Penalty'),
  ('Shelf Pin', 'Components'),
  ('4625', 'Paints'),
  ('Cartoon', 'Leather Materials'),
  ('Fuel for 2LT Pickup ', 'Fuel'),
  ('Door', 'Components'),
  ('MDF OverSized', 'MDF'),
  ('Crane', 'Machinery Rental '),
  ('VRF on ህዳር 2018', 'VRF '),
  ('Mop', 'Inventory'),
  ('CNC Punta by 6', 'Punta'),
  ('Veneer Gray', 'Veneer'),
  ('Sanitary Materials', 'Building Materials'),
  ('Toner', 'Office Inventory'),
  ('RHS ', 'Steel'),
  ('Hawassa MDF 18mm ', 'MDF'),
  ('RG 45', 'Electrical Materials'),
  ('Aluminum Track Channel', 'Aluminum'),
  ('Labor for Solomon Garden', 'Labor'),
  ('Grass', 'Components'),
  ('Sand Paper by 360', 'Sand Paper '),
  ('PPR Pipe by 25', 'Tap'),
  ('Veneer White', 'Veneer'),
  ('VRF on TIR 2018', 'VRF '),
  ('Aluminum Profile Office ', 'Aluminum'),
  ('Veneer UV White', 'Veneer'),
  ('A4 Paper ', 'Office Inventory'),
  ('Grinding Sand', 'Sand Paper '),
  ('Gypsum Work', 'Labor'),
  ('Aggregate Workers', 'Labor'),
  ('Water and Electricity Bill', 'Office Utility '),
  ('Nastro', 'Electrical Materials'),
  ('Disc 320', 'Tools'),
  ('Abeselom Loan ', 'Loan '),
  ('Gray Putty', 'Putty'),
  ('DNF Profit Tax', 'Government Expense'),
  ('Apel Foam', 'Foam'),
  ('C nail', 'Nail'),
  ('CNC Punta by 4', 'Punta'),
  ('Concert Admixture  ', 'Components'),
  ('Installation for Carpet', 'Other Services'),
  ('Jacuzzi', 'Components'),
  ('Bell Sou DingDong', 'Electrical Materials'),
  ('Trunking 10x20', 'Electrical Materials'),
  ('Labor for Wafa (AAICC)', 'Labor'),
  ('Jotun 1060', 'Paints'),
  ('MDF 18MM Asela', 'MDF'),
  ('Glass ', 'Glass'),
  ('Spuruso (coating)', 'Paints'),
  ('Waste Disposal ', 'Labor'),
  ('Chalk Blade', 'Tools'),
  ('Journal Paper', 'Office Expenses '),
  ('VRF on Yekatit 2018', 'VRF '),
  ('Abel''s Personal Payments', 'Loan '),
  ('Cement Board', 'Cement'),
  ('Trunking', 'Electrical Materials'),
  ('Metal bending ', 'Other Services'),
  ('Tap', 'Tap'),
  ('Veneer Mat', 'Veneer'),
  ('Angle', 'Steel'),
  ('2.5 Euro Wire', 'Electrical Materials'),
  ('Circle saw', 'Tools'),
  ('Aluminum Cladding Black', 'Aluminum'),
  ('MDF 18mm', 'MDF'),
  ('Jotun stucco ', 'Paints'),
  ('Conduit ', 'Electrical Materials'),
  ('Ppr reducer by 25x20', 'Tap'),
  ('U Aluminum ', 'Aluminum'),
  ('Screen Rent', 'Equipment Rental'),
  ('Clip', 'Electrical Materials'),
  ('Workshop Petty', 'PETTY'),
  ('L beret', 'Steel'),
  ('Scotch Tape', 'Electrical Materials'),
  ('9016 ', 'Paints'),
  ('JOTSH. TEX MEDUIIM WHITE 15 - Jotashild Tex Medium White 15L', 'Paints'),
  ('MDF 12MM', 'MDF'),
  ('Stage', 'Machinery Rental '),
  ('2.5x3 Cable', 'Electrical Materials'),
  ('Granite Polished H. Brown T-30', 'Granite'),
  ('Scaffolding ', 'Labor'),
  ('Olso 51', 'Building Materials'),
  ('Electrical Motorbike', 'Inventory'),
  ('Plastic glass (mayka)', 'Glass'),
  ('Scatola 10*10', 'Electrical Materials'),
  ('Wire cap', 'Electrical Materials'),
  ('Roller ', 'Building Materials'),
  ('Jotun 6032', 'Paints'),
  ('0099', 'Paints'),
  ('Plastic Bag', 'Plastic'),
  ('Shadow Drive', 'Electrical Materials'),
  ('Jotun 5004LUX', 'Paints'),
  ('Tire service ', 'Other Services'),
  ('Lamp 30w', 'Electrical Materials'),
  ('Nifas Silk Paint', 'Paints'),
  ('Yearly Tender Subscription', 'Marketing Expense'),
  ('Double Switch', 'Electrical Materials'),
  ('Single Socket', 'Electrical Materials'),
  ('Stapler Wire', 'Building Materials'),
  ('Anchor Bolt', 'Screw'),
  ('Jotun 0587', 'Paints'),
  ('Dinner For late night labor', 'Entertainment Expense '),
  ('Meter Tap by 5m', 'Tools'),
  ('MDF 8mm', 'MDF'),
  ('Balast for triple strip light', 'Electrical Materials'),
  ('Kacha', 'Building Materials'),
  ('Cutter', 'Tools'),
  ('Sand Paper by 120', 'Sand Paper '),
  ('CHS 50', 'Steel'),
  ('Isuzu ', 'Transportation'),
  ('Strip Light Drive', 'Electrical Materials'),
  ('Balast for Strip Light', 'Electrical Materials'),
  ('VAT WHT', 'Government Expense'),
  ('Labor for National Bank', 'Labor'),
  ('Slider Clamp', 'Building Materials'),
  ('Chalk Work', 'Labor'),
  ('PPR Tap 1/2', 'Tap'),
  ('Guroro Conduit 16', 'Electrical Materials'),
  ('Fasha', 'Building Materials'),
  ('Shooter Nail by 3', 'Nail'),
  ('IM) RCH MATT - Fenomastic Rch Matt (Im) Base B ', 'Paints'),
  ('T5 Light', 'Electrical Materials'),
  ('Package Plastic', 'Plastic'),
  ('Slider by 50cm', 'Components'),
  ('Brush', 'Tools'),
  ('VRF on ሀምሌ 2017', 'VRF '),
  ('IVECO Fuel', 'Fuel'),
  ('Coupling ', 'Building Materials'),
  ('Labor for Italy Africa', 'Labor'),
  ('Scatola 6*10', 'Electrical Materials'),
  ('Light Box', 'Components'),
  ('Waterproof light', 'Electrical Materials'),
  ('MDF WHITE 18MM', 'MDF'),
  ('Total Laser Level ', 'Tools'),
  ('Hydraulic Slider', 'Components'),
  ('Spray Mastish', 'Paints'),
  ('10235 summer sun', 'Paints'),
  ('Lamera', 'Steel'),
  ('Small Car Fuel', 'Fuel'),
  ('Aluminum Silver', 'Aluminum'),
  ('Overtime', 'Salary'),
  ('Gondar Personal Withdrawals ', 'Personal withdraws'),
  ('Solid Mat', 'UV Wood'),
  ('Cable HSS', 'Electrical Materials'),
  ('Thread bar by 8mm', 'Steel'),
  ('Cash Register Machine Cable', 'Office Inventory'),
  ('Receipt Printing', 'Government Expense')
)
UPDATE sub_categories sc
SET parent_category_id = c.id
FROM mapping m
JOIN categories c ON c.category_name = m.parent_name
WHERE sc.item_name = m.item_name
  AND sc.parent_category_id IS NULL;

-- ─── 3. Confirm the result ───
SELECT count(*) AS total_sub_categories,
       count(parent_category_id) AS rows_with_parent
FROM sub_categories;
