import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { HardHat, RefreshCw, ChevronRight, Play, Coins } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { useToast } from '@/contexts/ToastContext'
import { formatCurrency } from '@/lib/utils'

interface RollupPreview {
  worker_count: number
  total_units: number
  unit_label: string
  total_amount: number
}

interface DraftRow {
  id: string
  amount_etb: number | null
  date: string | null
  item_service_description: string | null
  approval_status: string
  payment_state: string
  rolled_up_from_requisition_id: string
  rollup_period_start: string | null
  rollup_period_end: string | null
  project_id: string
  projects: { project_name: string } | null
  vendor_id: string | null
  vendors: { vendor_name: string } | null
  paid_to_staff_id: string | null
  paid_to_staff: { employee_name: string } | null
}

interface RequisitionRow {
  id: string
  role_needed: string
  project_id: string
  payment_model: string
  pay_cycle: string
  start_date: string
  end_date: string | null
  estimated_total_cost: number | null
  projects: { project_name: string } | null
}

// Finance's rollup review page. Lists the auto-generated draft expenses from
// `rollup_labor_timesheets_to_expense` and offers a "Roll up now" launcher for
// the approved requisitions that don't have coverage for the last week yet.
export default function LaborExpenseDraftsPage() {
  const { toast } = useToast()
  const qc = useQueryClient()

  const { data: drafts = [], isLoading } = useQuery({
    queryKey: ['labor-expense-drafts'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('expenses')
        .select('id, amount_etb, date, item_service_description, approval_status, payment_state, rolled_up_from_requisition_id, rollup_period_start, rollup_period_end, project_id, projects(project_name), vendor_id, vendors(vendor_name), paid_to_staff_id, paid_to_staff:staff!expenses_paid_to_staff_id_fkey(employee_name)')
        .not('rolled_up_from_requisition_id', 'is', null)
        .order('date', { ascending: false })
      if (error) throw error
      return (data ?? []) as unknown as DraftRow[]
    },
  })

  const { data: activeReqs = [] } = useQuery({
    queryKey: ['approved-labor-requisitions'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('labor_requisitions')
        .select('id, role_needed, project_id, payment_model, pay_cycle, start_date, end_date, estimated_total_cost, projects(project_name)')
        .eq('status', 'approved')
        .order('start_date', { ascending: false })
      if (error) throw error
      return (data ?? []) as unknown as RequisitionRow[]
    },
  })

  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  function toggle(id: string) {
    setExpanded(s => { const o = new Set(s); if (o.has(id)) o.delete(id); else o.add(id); return o })
  }

  async function runRollup(requisitionId: string, from: string, to: string) {
    const { data, error } = await supabase.rpc('rollup_labor_timesheets_to_expense', {
      p_labor_requisition_id: requisitionId,
      p_period_start: from,
      p_period_end: to,
    })
    if (error) { toast(error.message, 'error'); return }
    toast(`Rollup complete → expense ${String(data).slice(0, 8)}`, 'success')
    qc.invalidateQueries({ queryKey: ['labor-expense-drafts'] })
    qc.invalidateQueries({ queryKey: ['labor-rollup-preview', requisitionId] })
  }

  const draftsByReq = useMemo(() => {
    const m = new Map<string, DraftRow[]>()
    for (const d of drafts) {
      const arr = m.get(d.rolled_up_from_requisition_id) ?? []
      arr.push(d); m.set(d.rolled_up_from_requisition_id, arr)
    }
    return m
  }, [drafts])

  // Default rollup window for the launcher — last week (Mon → Sun).
  const now = new Date()
  const day = now.getDay() // 0=Sun
  const lastSun = new Date(now); lastSun.setDate(now.getDate() - day)
  const lastMon = new Date(lastSun); lastMon.setDate(lastSun.getDate() - 6)
  const defaultFrom = lastMon.toISOString().slice(0, 10)
  const defaultTo   = lastSun.toISOString().slice(0, 10)

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-100 flex items-center gap-2">
          <HardHat className="h-6 w-6 text-amber-500" /> Labor Expense Drafts
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
          Draft expenses generated by timesheet rollup — one row per (requisition, period). Approve to send them into the To-Pay Queue.
        </p>
      </div>

      {/* Launcher: manual rollup for any approved requisition */}
      <div className="rounded-xl border bg-white dark:bg-slate-800 dark:border-slate-700 p-4">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-slate-700 dark:text-slate-200 flex items-center gap-2">
            <RefreshCw className="h-4 w-4" /> Run rollup
          </h2>
          <span className="text-[11px] text-slate-400">
            Default window: last week ({defaultFrom} → {defaultTo}). Scheduled runs need pg_cron enabled.
          </span>
        </div>
        {activeReqs.length === 0 ? (
          <p className="text-xs text-slate-400 py-4 text-center">No approved requisitions yet.</p>
        ) : (
          <div className="divide-y dark:divide-slate-700">
            {activeReqs.map(r => (
              <ReqRollupRow key={r.id} req={r} defaultFrom={defaultFrom} defaultTo={defaultTo} onRun={runRollup} />
            ))}
          </div>
        )}
      </div>

      {/* Drafts list */}
      <div className="rounded-xl border bg-white dark:bg-slate-800 dark:border-slate-700 overflow-hidden">
        <div className="px-4 py-3 border-b dark:border-slate-700 text-sm font-semibold text-slate-700 dark:text-slate-200">
          Generated drafts ({drafts.length})
        </div>
        {isLoading ? (
          <div className="py-12 text-center text-sm text-slate-400">Loading…</div>
        ) : drafts.length === 0 ? (
          <div className="py-12 text-center text-sm text-slate-400">No rollup drafts yet. Run one above.</div>
        ) : (
          <div>
            {[...draftsByReq.entries()].map(([reqId, rows]) => (
              <div key={reqId} className="border-b dark:border-slate-700 last:border-0">
                <div className="px-4 py-2 bg-slate-50 dark:bg-slate-900/40 text-xs text-slate-500">
                  Requisition <span className="font-mono">{reqId.slice(0, 8)}</span> · {rows[0].projects?.project_name ?? '—'} · {rows.length} draft{rows.length === 1 ? '' : 's'}
                </div>
                {rows.map(d => (
                  <DraftRow key={d.id} draft={d} expanded={expanded.has(d.id)} onToggle={() => toggle(d.id)} />
                ))}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function ReqRollupRow({ req, defaultFrom, defaultTo, onRun }: {
  req: RequisitionRow; defaultFrom: string; defaultTo: string;
  onRun: (id: string, from: string, to: string) => Promise<void>
}) {
  const [from, setFrom] = useState(defaultFrom)
  const [to, setTo]     = useState(defaultTo)
  const [busy, setBusy] = useState(false)

  const { data: preview, isFetching: previewLoading } = useQuery({
    queryKey: ['labor-rollup-preview', req.id, from, to],
    queryFn: async () => {
      const { data, error } = await supabase.rpc('preview_labor_rollup', {
        p_labor_requisition_id: req.id, p_period_start: from, p_period_end: to,
      })
      if (error) throw error
      return (data?.[0] ?? null) as RollupPreview | null
    },
    enabled: !!from && !!to,
  })

  const owes = (preview?.total_amount ?? 0) > 0

  return (
    <div className="py-3 flex items-center gap-3 flex-wrap">
      <div className="min-w-0 flex-1">
        <p className="text-sm font-medium text-slate-700 dark:text-slate-200">{req.role_needed} · {req.projects?.project_name ?? '—'}</p>
        <p className="text-[11px] text-slate-400">
          {req.payment_model} · {req.pay_cycle} · est. {req.estimated_total_cost != null ? formatCurrency(req.estimated_total_cost) : '—'}
        </p>
      </div>
      <input type="date" value={from} onChange={e => setFrom(e.target.value)} className="text-xs rounded border dark:bg-slate-800 dark:border-slate-600 dark:text-slate-100 px-2 py-1" />
      <input type="date" value={to}   onChange={e => setTo(e.target.value)}   className="text-xs rounded border dark:bg-slate-800 dark:border-slate-600 dark:text-slate-100 px-2 py-1" />
      <div className={`flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium tabular-nums ${
        previewLoading ? 'text-slate-400' : owes ? 'bg-amber-50 text-amber-700 dark:bg-amber-900/20 dark:text-amber-300' : 'text-slate-400'
      }`}>
        <Coins className="h-3 w-3" />
        {previewLoading ? 'Checking…' : owes
          ? <>Owes {formatCurrency(preview!.total_amount)} <span className="font-normal text-[10px] opacity-80">· {preview!.worker_count} worker{preview!.worker_count === 1 ? '' : 's'} · {preview!.total_units} {preview!.unit_label}</span></>
          : 'Nothing owed in this window'}
      </div>
      <button
        onClick={async () => { setBusy(true); try { await onRun(req.id, from, to) } finally { setBusy(false) } }}
        disabled={busy || previewLoading || !owes}
        className="flex items-center gap-1 rounded-md bg-brand px-3 py-1.5 text-xs font-medium text-white hover:bg-brand/90 disabled:opacity-40"
      >
        <Play className="h-3 w-3" /> {busy ? 'Rolling…' : 'Roll up'}
      </button>
    </div>
  )
}

function DraftRow({ draft, expanded, onToggle }: { draft: DraftRow; expanded: boolean; onToggle: () => void }) {
  const { data: workers = [] } = useQuery({
    queryKey: ['labor-expense-workers', draft.id],
    enabled: expanded,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('labor_expense_workers')
        .select('id, staff_id, days_worked, day_rate, subtotal, staff(employee_name)')
        .eq('expense_id', draft.id)
      if (error) throw error
      return data ?? []
    },
  })

  return (
    <div>
      <button onClick={onToggle} className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-50 dark:hover:bg-slate-700/40 text-left">
        <ChevronRight className={`h-4 w-4 text-slate-400 transition-transform ${expanded ? 'rotate-90' : ''}`} />
        <div className="min-w-0 flex-1">
          <p className="text-sm text-slate-700 dark:text-slate-200 truncate">{draft.item_service_description ?? '—'}</p>
          <p className="text-[11px] text-slate-400">
            {draft.rollup_period_start} → {draft.rollup_period_end}
            {draft.vendors?.vendor_name ? ` · Gang: ${draft.vendors.vendor_name}` : ''}
            {draft.paid_to_staff?.employee_name ? ` · Payee: ${draft.paid_to_staff.employee_name}` : ''}
          </p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-slate-800 dark:text-slate-100 tabular-nums">{formatCurrency(draft.amount_etb ?? 0)}</p>
          <p className="text-[11px] text-slate-400 capitalize">{draft.approval_status} · {draft.payment_state}</p>
        </div>
        <Link to={`/expenses/${draft.id}`} className="text-[11px] text-brand hover:underline" onClick={e => e.stopPropagation()}>
          Open expense →
        </Link>
      </button>
      {expanded && (
        <div className="px-8 pb-3">
          <div className="rounded-lg border dark:border-slate-700 overflow-hidden">
            <table className="w-full text-xs">
              <thead className="bg-slate-50 dark:bg-slate-900/40">
                <tr>
                  <th className="text-left px-3 py-2 font-medium text-slate-500">Worker</th>
                  <th className="text-right px-3 py-2 font-medium text-slate-500">Days</th>
                  <th className="text-right px-3 py-2 font-medium text-slate-500">Rate</th>
                  <th className="text-right px-3 py-2 font-medium text-slate-500">Subtotal</th>
                </tr>
              </thead>
              <tbody className="divide-y dark:divide-slate-700">
                {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                {(workers as any[]).map(w => (
                  <tr key={w.id}>
                    <td className="px-3 py-2 text-slate-700 dark:text-slate-200">{w.staff?.employee_name ?? '—'}</td>
                    <td className="px-3 py-2 text-right tabular-nums">{w.days_worked}</td>
                    <td className="px-3 py-2 text-right tabular-nums">{formatCurrency(w.day_rate)}</td>
                    <td className="px-3 py-2 text-right tabular-nums font-semibold">{formatCurrency(w.subtotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-[10px] text-slate-400 mt-2">
            Timesheets covered by this draft have <span className="font-mono">rolled_up_expense_id = {draft.id.slice(0, 8)}</span> and won't roll up again.
          </p>
        </div>
      )}
    </div>
  )
}
