-- ============================================================
-- Stop expense_code from silently changing after it's been assigned.
--
-- trg_generate_expense_code (006_expense_workflow.sql) fires on
-- `BEFORE INSERT OR UPDATE OF project_id, category_id, date` and,
-- per the guard patched in migration 042, only skips regeneration when
-- `TG_OP = 'INSERT' AND NEW.expense_code IS NOT NULL`. That guard does
-- nothing for UPDATE: every time an expense's project, category, or
-- date is edited — including by a normal user in the app, and by the
-- project_id backfill in migration 065 — the trigger overwrites
-- expense_code with a freshly computed value, discarding whatever was
-- there before (e.g. the original Airtable-format code like
-- "PAI-C+-JOT-SIL-250709-ONE" silently becomes something like
-- "JOTU-MISC-20250709-01").
--
-- expense_code is a durable reference number — it's printed on POs,
-- used as a lookup key, and was the join key attempted in migration
-- 066. It should never change once assigned, regardless of what
-- caused the trigger to fire. The only case that should generate one
-- is when a row doesn't have one yet.
-- ============================================================

BEGIN;

CREATE OR REPLACE FUNCTION generate_expense_code()
RETURNS TRIGGER AS $$
DECLARE
  v_project_tag TEXT;
  v_ledger_tag  TEXT;
  v_date_tag    TEXT;
  v_prefix      TEXT;
  v_seq         INT;
BEGIN
  IF NEW.expense_code IS NOT NULL THEN
    RETURN NEW;
  END IF;

  SELECT UPPER(LEFT(REGEXP_REPLACE(project_name, '[^A-Za-z0-9]', '', 'g'), 4))
    INTO v_project_tag FROM projects WHERE id = NEW.project_id;
  SELECT UPPER(LEFT(REGEXP_REPLACE(category_name, '[^A-Za-z0-9]', '', 'g'), 4))
    INTO v_ledger_tag FROM categories WHERE id = NEW.category_id;

  v_project_tag := COALESCE(NULLIF(v_project_tag, ''), 'GEN');
  v_ledger_tag  := COALESCE(NULLIF(v_ledger_tag, ''), 'MISC');
  v_date_tag    := TO_CHAR(COALESCE(NEW.date, CURRENT_DATE), 'YYYYMMDD');
  v_prefix      := v_project_tag || '-' || v_ledger_tag || '-' || v_date_tag;

  SELECT COUNT(*) + 1 INTO v_seq
  FROM expenses
  WHERE expense_code LIKE v_prefix || '-%'
    AND id IS DISTINCT FROM NEW.id;

  NEW.expense_code := v_prefix || '-' || LPAD(v_seq::TEXT, 2, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMIT;

-- Diagnostic: how many rows currently carry a code that was already
-- silently regenerated by the old buggy trigger (matches the
-- TAG-TAG-YYYYMMDD-## shape this function produces, as opposed to
-- Airtable's original TAG-GRADE-TAG-TAG-YYMMDD-INITIALS shape).
SELECT count(*) AS likely_regenerated_codes
FROM expenses
WHERE expense_code ~ '-[0-9]{8}-[0-9]{2}$';
